#[path = "easy/1.two-sum.rs"]
pub mod problem_1;
#[path = "easy/100.same-tree.rs"]
pub mod problem_100;
#[path = "easy/101.symmetric-tree.rs"]
pub mod problem_101;
#[path = "easy/104.maximum-depth-of-binary-tree.rs"]
pub mod problem_104;
#[path = "easy/108.convert-sorted-array-to-binary-search-tree.rs"]
pub mod problem_108;
#[path = "easy/110.balanced-binary-tree.rs"]
pub mod problem_110;
#[path = "easy/111.minimum-depth-of-binary-tree.rs"]
pub mod problem_111;
#[path = "easy/112.path-sum.rs"]
pub mod problem_112;
#[path = "easy/118.pascals-triangle.rs"]
pub mod problem_118;
#[path = "easy/119.pascals-triangle-ii.rs"]
pub mod problem_119;
#[path = "easy/13.roman-to-integer.rs"]
pub mod problem_13;
#[path = "easy/14.longest-common-prefix.rs"]
pub mod problem_14;
#[path = "easy/20.valid-parentheses.rs"]
pub mod problem_20;
#[path = "easy/21.merge-two-sorted-lists.rs"]
pub mod problem_21;
#[path = "easy/26.remove-duplicates-from-sorted-array.rs"]
pub mod problem_26;
#[path = "easy/27.remove-element.rs"]
pub mod problem_27;
#[path = "easy/35.search-insert-position.rs"]
pub mod problem_35;
#[path = "easy/58.length-of-last-word.rs"]
pub mod problem_58;
#[path = "easy/66.plus-one.rs"]
pub mod problem_66;
#[path = "easy/67.add-binary.rs"]
pub mod problem_67;
#[path = "easy/69.sqrt-x.rs"]
pub mod problem_69;
#[path = "easy/70.climbing-stairs.rs"]
pub mod problem_70;
#[path = "easy/83.remove-duplicates-from-sorted-list.rs"]
pub mod problem_83;
#[path = "easy/88.merge-sorted-array.rs"]
pub mod problem_88;
#[path = "easy/9.palindrome-number.rs"]
pub mod problem_9;
#[path = "easy/94.binary-tree-inorder-traversal.rs"]
pub mod problem_94;

fn main() {
    println!("Hello, world!");
}
